apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-17T21:06:44Z"
  generateName: sa-wordpress-54886b8cb-
  labels:
    app.kubernetes.io/instance: sa-wordpress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.4.1
    helm.sh/chart: wordpress-18.1.14
    pod-template-hash: 54886b8cb
  name: sa-wordpress-54886b8cb-mxskk
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: sa-wordpress-54886b8cb
    uid: 3299558b-2a85-4fa2-a9f6-b85fe36ea232
  resourceVersion: "1864364"
  uid: 76d9c2a7-a4a9-44ff-ac6f-f97153f817e5
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: sa-wordpress
              app.kubernetes.io/name: wordpress
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: MARIADB_HOST
      value: 192.168.202.14
    - name: MARIADB_PORT_NUMBER
      value: "3306"
    - name: WORDPRESS_DATABASE_NAME
      value: wordpressdb
    - name: WORDPRESS_DATABASE_USER
      value: sasha@%
    - name: WORDPRESS_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: sa-wordpress-externaldb
    - name: WORDPRESS_USERNAME
      value: user
    - name: WORDPRESS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: wordpress-password
          name: sa-wordpress
    - name: WORDPRESS_EMAIL
      value: mazurovsasha@gmail.com
    - name: WORDPRESS_FIRST_NAME
      value: Aleksandr
    - name: WORDPRESS_LAST_NAME
      value: Mazurov
    - name: WORDPRESS_HTACCESS_OVERRIDE_NONE
      value: "no"
    - name: WORDPRESS_ENABLE_HTACCESS_PERSISTENCE
      value: "no"
    - name: WORDPRESS_BLOG_NAME
      value: Mazurov's Blog!
    - name: WORDPRESS_SKIP_BOOTSTRAP
      value: "no"
    - name: WORDPRESS_TABLE_PREFIX
      value: wp_
    - name: WORDPRESS_SCHEME
      value: http
    - name: WORDPRESS_EXTRA_WP_CONFIG_CONTENT
    - name: WORDPRESS_PLUGINS
      value: none
    - name: APACHE_HTTP_PORT_NUMBER
      value: "8080"
    - name: APACHE_HTTPS_PORT_NUMBER
      value: "8443"
    image: docker.io/bitnami/wordpress:6.4.1-debian-11-r4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /wp-admin/install.php
        port: http
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: wordpress
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /wp-login.php
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: wordpress-data
      subPath: wordpress
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-55zbd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostAliases:
  - hostnames:
    - status.localhost
    ip: 127.0.0.1
  nodeName: debian10
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: wordpress-data
    persistentVolumeClaim:
      claimName: sa-wordpress
  - name: kube-api-access-55zbd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-17T21:06:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-11-25T11:32:10Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-11-25T11:32:10Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-17T21:06:49Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://593090fcddcf9cb6347d9a3e5b66d1d9aae3e1949431a9d227c45d4fd549597a
    image: docker.io/bitnami/wordpress:6.4.1-debian-11-r4
    imageID: docker.io/bitnami/wordpress@sha256:31c8545e6a9c55b3c8d98c198322d613aefdfa1a41d3dcde591d3f89a81bb219
    lastState:
      terminated:
        containerID: containerd://0b4394047f7be10ff0ceacc2882ebad49aa749d4019642037ad73d8657c9eef4
        exitCode: 0
        finishedAt: "2023-11-25T11:31:26Z"
        reason: Completed
        startedAt: "2023-11-24T11:27:55Z"
    name: wordpress
    ready: true
    restartCount: 7
    started: true
    state:
      running:
        startedAt: "2023-11-25T11:31:31Z"
  hostIP: 192.168.203.7
  phase: Running
  podIP: 10.42.0.144
  podIPs:
  - ip: 10.42.0.144
  qosClass: Burstable
  startTime: "2023-11-17T21:06:49Z"
