apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-11-25T08:22:12Z"
  generation: 87
  name: first-app
  namespace: argocd
  resourceVersion: "1866080"
  uid: 310e8a01-2fe6-4cea-a297-c025983bc915
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    repoURL: https://mazurovsasha.github.io/helm-test/
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-11-25T08:22:15Z"
    deployedAt: "2023-11-25T08:22:17Z"
    id: 0
    revision: 0.2.0
    source:
      chart: first-app
      repoURL: https://mazurovsasha.github.io/helm-test/
      targetRevision: 0.2.0
  operationState:
    finishedAt: "2023-11-25T08:22:17Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 0.2.0
    phase: Succeeded
    startedAt: "2023-11-25T08:22:15Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: 'serviceaccount/first-app configured. Warning: resource serviceaccounts/first-app
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: 'persistentvolumeclaim/pv-claim-helm configured. Warning: resource
          persistentvolumeclaims/pv-claim-helm is missing the kubectl.kubernetes.io/last-applied-configuration
          annotation which is required by  apply.  apply should only be used on resources
          created declaratively by either  create --save-config or  apply. The missing
          annotation will be patched automatically.'
        name: pv-claim-helm
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: 'service/first-app configured. Warning: resource services/first-app
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: 'deployment.apps/first-app configured. Warning: resource deployments/first-app
          is missing the kubectl.kubernetes.io/last-applied-configuration annotation
          which is required by  apply.  apply should only be used on resources created
          declaratively by either  create --save-config or  apply. The missing annotation
          will be patched automatically.'
        name: first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/first-app created
        name: first-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.2.0
      source:
        chart: first-app
        repoURL: https://mazurovsasha.github.io/helm-test/
        targetRevision: 0.2.0
  reconciledAt: "2023-11-25T12:02:37Z"
  resources:
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: pv-claim-helm
    namespace: default
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: first-app
    namespace: default
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: first-app
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: first-app
    namespace: default
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: first-app
    namespace: default
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://helm.k8s-15.sa/
    images:
    - eboraas/apache-php:latest
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        chart: first-app
        repoURL: https://mazurovsasha.github.io/helm-test/
        targetRevision: 0.2.0
    revision: 0.2.0
    status: Synced
